title: Yisong Miao 苗屹松
url: "https://yisong.me"
#baseurl: "/researcher"

nav:
#  - name: "About"
#    link: "/researcher/"
#  - name: "Resume"
#    link: "resume.pdf"
 # - name: "UCMW Project"
 #   link: "https://yisong.me/UCMW/index"
 - name: "MLP Blog"
   link: "https://yisong.me/MLP"
 - name: "Readings"
   link: "https://yisong.me/readings"
 # - name: "Friends"
 #   link: "https://yisong.me/friends"
 - name: "Home"
   link: "https://yisong.me"

 # - name: "CV"
 #   link: "https://yisong.me/Yisong-CV-2021-Feb.pdf"

#theme: jekyll-theme-cayman
#remote_theme: ankitsultana/researcher@gem
#theme: ankitsultana/researcher@gem

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
