title: Yisong Miao 苗屹松
url: "https://yisong.me"
#baseurl: "/researcher"

nav:
#  - name: "About"
#    link: "/researcher/"
#  - name: "Resume"
#    link: "resume.pdf"
 # - name: "UCMW Project"
 #   link: "https://yisong.me/UCMW/index"
 - name: "What's New?"
   link: "https://yisong.me/progress-log"
 - name: "Meta Research"
   link: "https://yisong.me/meta"
 - name: "CV"
   link: "https://yisong.me/Yisong-cv-2020may-officialpubs.pdf"
 - name: "Home"
   link: "https://yisong.me"

#theme: jekyll-theme-cayman
#remote_theme: ankitsultana/researcher@gem
#theme: ankitsultana/researcher@gem

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass